title: sem-tec
description: Um caderno semântico de tecnologia
author: jultty
baseurl: ""
domain: jultty.github.io
url: "https://jultty.github.io"
permalink: /:categories/:title:output_ext
twitter_username: 
github_username: jultty 
avatar_url: /assets/images/venn.svg
favicon: favicon.ico

# Build settings
#theme: moving
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

collections:
    tags:
        output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

